---
- name: Copy update-exim4.conf.conf
  template: src=update-exim4.j2
            dest=/etc/exim4/update-exim4.conf.conf mode=0664 owner=root
            group=root
  notify:
    - restart exim4

- name: Copy /etc/default/exim4
  template: src=exim4.j2 dest=/etc/default/exim4 mode=0644 owner=root group=root
  notify:
    - restart exim4

- name: Configure hubbed hosts
  template: src=hubbed_hosts.j2 dest=/etc/exim4/hubbed_hosts
  when: exim4_hubbed_hosts is defined
  notify:
    - restart exim4

- name: Copy localmacros
  template:
    src: localmacros.j2
    dest: /etc/exim4/conf.d/main/000_localmacros
  notify:
    - restart exim4
